-- Engineering Project Management System: Supabase multi-user schema
-- Run this complete file once in Supabase Dashboard -> SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 200),
  data jsonb not null default '{"progress":[],"materials":[],"labor":[],"daily":[]}'::jsonb,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.project_members (
  project_id bigint not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('viewer', 'editor')),
  created_at timestamptz not null default now(),
  primary key (project_id, user_id)
);

create table if not exists public.material_masters (
  id bigint generated by default as identity primary key,
  name text not null,
  unit text not null,
  price numeric(14,2) not null default 0 check (price >= 0),
  created_by uuid not null default auth.uid() references auth.users(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.labor_masters (
  id bigint generated by default as identity primary key,
  name text not null,
  unit text not null default '日',
  price numeric(14,2) not null default 0 check (price >= 0),
  created_by uuid not null default auth.uid() references auth.users(id),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email, ''), '@', 1)))
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of email on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.can_access_project(target_project_id bigint)
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.projects p
    where p.id = target_project_id
      and (p.owner_id = auth.uid() or exists (
        select 1 from public.project_members pm
        where pm.project_id = p.id and pm.user_id = auth.uid()
      ))
  );
$$;

create or replace function public.can_edit_project(target_project_id bigint)
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.projects p
    where p.id = target_project_id
      and (p.owner_id = auth.uid() or exists (
        select 1 from public.project_members pm
        where pm.project_id = p.id and pm.user_id = auth.uid() and pm.role = 'editor'
      ))
  );
$$;

create or replace function public.add_project_member_by_email(
  target_project_id bigint,
  member_email text,
  member_role text default 'editor'
)
returns void
language plpgsql
security definer set search_path = public, auth
as $$
declare
  target_user_id uuid;
begin
  if member_role not in ('viewer', 'editor') then
    raise exception 'Invalid member role';
  end if;
  if not exists (
    select 1 from public.projects
    where id = target_project_id and owner_id = auth.uid()
  ) then
    raise exception 'Only the project owner can manage members';
  end if;
  select id into target_user_id from auth.users where lower(email) = lower(trim(member_email));
  if target_user_id is null then
    raise exception 'User must sign up before being added';
  end if;
  if target_user_id = auth.uid() then
    raise exception 'The owner is already a project member';
  end if;
  insert into public.project_members (project_id, user_id, role)
  values (target_project_id, target_user_id, member_role)
  on conflict (project_id, user_id) do update set role = excluded.role;
end;
$$;

revoke all on function public.add_project_member_by_email(bigint, text, text) from public;
grant execute on function public.add_project_member_by_email(bigint, text, text) to authenticated;
grant execute on function public.can_access_project(bigint) to authenticated;
grant execute on function public.can_edit_project(bigint) to authenticated;

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.material_masters enable row level security;
alter table public.labor_masters enable row level security;

drop policy if exists "profiles readable by authenticated users" on public.profiles;
create policy "profiles readable by authenticated users" on public.profiles
  for select to authenticated using (true);
drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "members read projects" on public.projects;
create policy "members read projects" on public.projects
  for select to authenticated using (public.can_access_project(id));
drop policy if exists "users create projects" on public.projects;
create policy "users create projects" on public.projects
  for insert to authenticated with check (owner_id = auth.uid());
drop policy if exists "editors update projects" on public.projects;
create policy "editors update projects" on public.projects
  for update to authenticated using (public.can_edit_project(id)) with check (public.can_edit_project(id));
drop policy if exists "owners delete projects" on public.projects;
create policy "owners delete projects" on public.projects
  for delete to authenticated using (owner_id = auth.uid());

drop policy if exists "members read memberships" on public.project_members;
create policy "members read memberships" on public.project_members
  for select to authenticated using (public.can_access_project(project_id));
drop policy if exists "owners add memberships" on public.project_members;
create policy "owners add memberships" on public.project_members
  for insert to authenticated with check (
    exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid())
  );
drop policy if exists "owners update memberships" on public.project_members;
create policy "owners update memberships" on public.project_members
  for update to authenticated using (
    exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid())
  );
drop policy if exists "owners remove memberships" on public.project_members;
create policy "owners remove memberships" on public.project_members
  for delete to authenticated using (
    exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid())
  );

drop policy if exists "authenticated read material masters" on public.material_masters;
create policy "authenticated read material masters" on public.material_masters
  for select to authenticated using (true);
drop policy if exists "authenticated create material masters" on public.material_masters;
create policy "authenticated create material masters" on public.material_masters
  for insert to authenticated with check (created_by = auth.uid());
drop policy if exists "authenticated update material masters" on public.material_masters;
create policy "authenticated update material masters" on public.material_masters
  for update to authenticated using (true) with check (true);
drop policy if exists "authenticated delete material masters" on public.material_masters;
create policy "authenticated delete material masters" on public.material_masters
  for delete to authenticated using (true);

drop policy if exists "authenticated read labor masters" on public.labor_masters;
create policy "authenticated read labor masters" on public.labor_masters
  for select to authenticated using (true);
drop policy if exists "authenticated create labor masters" on public.labor_masters;
create policy "authenticated create labor masters" on public.labor_masters
  for insert to authenticated with check (created_by = auth.uid());
drop policy if exists "authenticated update labor masters" on public.labor_masters;
create policy "authenticated update labor masters" on public.labor_masters
  for update to authenticated using (true) with check (true);
drop policy if exists "authenticated delete labor masters" on public.labor_masters;
create policy "authenticated delete labor masters" on public.labor_masters
  for delete to authenticated using (true);

create index if not exists project_members_user_idx on public.project_members(user_id);
create index if not exists projects_owner_idx on public.projects(owner_id);
